name: iJoiner
version: '${project.version}'
main: dev.twilightsociety.ijoiner.iJoiner
api-version: '1.18'
softdepend: [PlaceholderAPI]
authors: [Igram4ik]
description: Плагин на приветствие
commands:
  ijoiner:
